# Generated by Django 4.1.5 on 2023-01-25 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0002_category_menuitem_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="menuitem", name="category",),
    ]
